language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
before_install:
- sudo apt-get update -qq
- sudo apt-get install libfreetype6-dev
- sudo apt-get install libgeos-c1 libgeos-dev
install:
- pip install .
- pip install coveralls
- pip install pykdtree
script: coverage run --source=pyresample setup.py test
after_success: coveralls
