name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - xarray
  - zarr
  - dask
  - toolz
  - numpy
  - cython
  - cartopy
  - pytest
  - proj4
  - pyproj
  - shapely
  - pykdtree
